In [1]:
# DEFINE THE DATASET IN A WAY THAT SCIKIT.LEARN CAN USE:
train_set = ("The sky is blue.", 
             "The sun is bright.")
test_set = ("The sun in the sky is bright.",
            "We can see the shining sun, the bright sun.")

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [3]:
print(vectorizer)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [4]:
vectorizer.fit_transform(train_set)
print(vectorizer.vocabulary)

None


In [8]:
smatrix = vectorizer.transform(train_set)

In [9]:
print(smatrix)

  (0, 0)	1
  (0, 2)	1
  (0, 3)	1
  (0, 5)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (1, 5)	1


In [10]:
smatrix.todense()

matrix([[1, 0, 1, 1, 0, 1],
        [0, 1, 1, 0, 1, 1]], dtype=int64)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
train_set = ("The sky is blue.", "The sun is bright.")
test_set = ("The sun in the sky is bright.",
"We can see the shining sun, the bright sun.")
count_vectorizer = CountVectorizer()
count_vectorizer.fit_transform(train_set)
print("Vocabulary:", count_vectorizer.vocabulary)
# Vocabulary: {'blue': 0, 'sun': 1, 'bright': 2, 'sky': 3}
freq_term_matrix = count_vectorizer.transform(test_set)
print(freq_term_matrix.todense())

Vocabulary: None
[[0 1 1 1 1 2]
 [0 1 0 0 2 2]]


In [14]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(freq_term_matrix)
print("IDF:", tfidf.idf_)

IDF: [ 2.09861229  1.          1.40546511  1.40546511  1.          1.        ]


In [15]:
tf_idf_matrix = tfidf.transform(freq_term_matrix)
print(tf_idf_matrix.todense())

[[ 0.          0.31701073  0.44554752  0.44554752  0.31701073  0.63402146]
 [ 0.          0.33333333  0.          0.          0.66666667  0.66666667]]
